TestDev/TrueWheels.Web/Controllers/RentSpaceController.cs
using Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrueWheels.BEL;
using TrueWheels.DAL;
using TrueWheels.Web.Models;

namespace TrueWheels.Web.Controllers
{
    public class RentSpaceController : Controller
    {
        //
        // GET: /RentSpace/
        public ActionResult CreateSpace()
        {
            return View();
        }

        public ActionResult UploadSpace(HttpPostedFileBase upload)
        {
            var lat = string.Empty;
            var lng = string.Empty;
            if (ModelState.IsValid)
            {

                if (upload != null && upload.ContentLength > 0)
                {
                    // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                    // to get started. This is how we avoid dependencies on ACE or Interop:
                    Stream stream = upload.InputStream;

                    // We return the interface, so that
                    IExcelDataReader reader = null;


                    if (upload.FileName.EndsWith(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (upload.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "This file format is not supported");
                        return View();
                    }

                    reader.IsFirstRowAsColumnNames = true;
                    //reader.
                    DataSet result = reader.AsDataSet();
                    reader.Close();
                    // start
                    DataColumn column = new DataColumn();
                    column.ColumnName = "Registered";
                    result.Tables[0].Columns.Add(column);
                    column = new DataColumn();
                    column.ColumnName = "ErrorMessage";
                    result.Tables[0].Columns.Add(column);
                    ParkingAreaDAL Parkingdal = new ParkingAreaDAL();
                    RegisterParkingAreaBEL ParkingBEL = new RegisterParkingAreaBEL();
                    RegsiterParkingAreaResult ParkingResult = new RegsiterParkingAreaResult();
                    for (int i=0;i<=result.Tables[0].Rows.Count-1;i++)
                    {
                        ParkingResult.ErrorMessage = "";
                        if (result.Tables[0].Rows[i]["owner_id"] != null && Convert.ToString(result.Tables[0].Rows[i]["owner_id"]) != "")
                            ParkingBEL.owner_id = Convert.ToInt32(result.Tables[0].Rows[i]["owner_id"]);
                        else
                            ParkingResult.ErrorMessage = "owner id can not be blank. ";

                        if (result.Tables[0].Rows[i]["Space_type"] != null && Convert.ToString(result.Tables[0].Rows[i]["Space_type"]) != "")
                           ParkingBEL.Space_type = Convert.ToString(result.Tables[0].Rows[i]["Space_type"]);
                        else
                            ParkingResult.ErrorMessage += " Space_type can not be blank. ";

                        if (result.Tables[0].Rows[i]["Property_type"] != null && Convert.ToString(result.Tables[0].Rows[i]["Property_type"]) != "")
                           ParkingBEL.Property_type = Convert.ToString(result.Tables[0].Rows[i]["Property_type"]);
                        else
                            ParkingResult.ErrorMessage += " Property_type can not be blank. ";

                        if (result.Tables[0].Rows[i]["No_of_space"] != null && Convert.ToString(result.Tables[0].Rows[i]["No_of_space"]) != "" )
                        ParkingBEL.No_of_space = Convert.ToString(result.Tables[0].Rows[i]["No_of_space"]);
                        else
                            ParkingResult.ErrorMessage += " No_of_space can not be blank. ";

                        if (result.Tables[0].Rows[i]["VechileType"] != null && Convert.ToString(result.Tables[0].Rows[i]["VechileType"]) != "")
                        ParkingBEL.VechileType = Convert.ToString(result.Tables[0].Rows[i]["VechileType"]);
                        else
                            ParkingResult.ErrorMessage += " VechileType can not be blank. ";

                        if (result.Tables[0].Rows[i]["PropertyVerifiedStatus"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyVerifiedStatus"]) != "")
                        ParkingBEL.PropertyVerifiedStatus = Convert.ToString(result.Tables[0].Rows[i]["PropertyVerifiedStatus"]);
                        else
                            ParkingResult.ErrorMessage += " PropertyVerifiedStatus can not be blank. ";

                        ParkingBEL.FacilityGroupId = Convert.ToString(result.Tables[0].Rows[i]["FacilityGroupId"]);

                        if (result.Tables[0].Rows[i]["PropertyAddress"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyAddress"]) != "")
                        {
                            ParkingBEL.PropertyAddress = Convert.ToString(result.Tables[0].Rows[i]["PropertyAddress"]);
                            HomeController.GetLatLongByLocation(ParkingBEL.PropertyAddress, ref lat, ref lng);
                        }
                        else
                            ParkingResult.ErrorMessage += " No_of_space can not be blank. ";

                        if (result.Tables[0].Rows[i]["PropertyPinCode"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyPinCode"]) != "")
                        ParkingBEL.PropertyPinCode = Convert.ToInt32(result.Tables[0].Rows[i]["PropertyPinCode"]);
                        else
                            ParkingResult.ErrorMessage += " PropertyPinCode can not be blank. ";

                        ParkingBEL.PropertyZone = Convert.ToString(result.Tables[0].Rows[i]["PropertyZone"]);

                        ParkingBEL.PropertyLandMark = Convert.ToString(result.Tables[0].Rows[i]["PropertyLandMark"]);

                        ParkingBEL.OwnerComments = Convert.ToString(result.Tables[0].Rows[i]["OwnerComments"]);

                        

                        if (result.Tables[0].Rows[i]["lattitude"] != null && Convert.ToString(result.Tables[0].Rows[i]["lattitude"]) != "")
                            ParkingBEL.lattitude = Convert.ToString(result.Tables[0].Rows[i]["lattitude"]);
                        else 

                        {
                            if (string.IsNullOrWhiteSpace(Convert.ToString(lat)))
                            ParkingResult.ErrorMessage += " lattitude can not be blank. "; 
                            else
                                ParkingBEL.lattitude = Convert.ToString(lat);

                        }

                        if (result.Tables[0].Rows[i]["longitude"] != null && Convert.ToString(result.Tables[0].Rows[i]["longitude"]) != "")
                            ParkingBEL.longitude = Convert.ToString(result.Tables[0].Rows[i]["longitude"]);
                        else
                        {
                            if (string.IsNullOrWhiteSpace(Convert.ToString(lng)))
                                ParkingResult.ErrorMessage += " longitude can not be blank. "; 
                            else
                                ParkingBEL.longitude = Convert.ToString(lng);
                        }


                        if (ParkingResult.ErrorMessage == "")
                        {
                            ParkingResult = Parkingdal.RegisterParkingAreaUploadFile(ParkingBEL);

                            if (ParkingResult.ErrorMessage == "" && ParkingResult.Parking_Id != 0)
                            {
                                result.Tables[0].Rows[i]["Registered"] = "True";

                            }
                            else
                            {
                                result.Tables[0].Rows[i]["Registered"] = "False";
                                result.Tables[0].Rows[i]["ErrorMessage"] = ParkingResult.ErrorMessage;
                            }
                        }
                        else
                        {
                            result.Tables[0].Rows[i]["Registered"] = "False";
                            result.Tables[0].Rows[i]["ErrorMessage"] = ParkingResult.ErrorMessage;
                        }
                    }
                    // end
                    return View(result.Tables[0]);
                }
                else
                {
                    ModelState.AddModelError("File", "Please Upload Your file");
                }
            }
            return View();
        }
    }
}

TestDev/TrueWheels.Web/Views/RentSpace/CreateSpace.cshtml
@model TrueWheels.Web.Models.RentYourSpaceViewModel

@{
    ViewBag.Title = "CreateSpace";
}

<h2>CreateSpace</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RentYourSpaceViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.User_Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Name)
                @Html.ValidationMessageFor(model => model.User_Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_No1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_No1)
                @Html.ValidationMessageFor(model => model.Phone_No1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email_Id)
                @Html.ValidationMessageFor(model => model.Email_Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.First_Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.First_Name)
                @Html.ValidationMessageFor(model => model.First_Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Last_Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Last_Name)
                @Html.ValidationMessageFor(model => model.Last_Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owner_Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner_Address)
                @Html.ValidationMessageFor(model => model.Owner_Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_No2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_No2)
                @Html.ValidationMessageFor(model => model.Phone_No2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alternate_Email_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alternate_Email_Id)
                @Html.ValidationMessageFor(model => model.Alternate_Email_Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SignUp_Mode_ID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SignUp_Mode_ID)
                @Html.ValidationMessageFor(model => model.SignUp_Mode_ID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestDev/TrueWheels.Web/Views/RentSpace/UploadSpace.cshtml

@{
    ViewBag.Title = "UploadSpace";
}

@model System.Data.DataTable
@using System.Data;

<h2>Upload File</h2>

@using (Html.BeginForm("UploadSpace", "RentSpace", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-group">
        <input type="file" id="dataFile" name="upload" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-default" />
    </div>

    if (Model != null)
    {
        <table border="1">
            <thead>
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <th style="background-color:darkgreen;color:white;">@col.ColumnName</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
}
