TestDev/TrueWheels.Web/Models/ParkingAreaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TrueWheels.Web.Models
{

    public class ParkingAreaViewModel
    {

        public decimal Main_Latitude { get; set; }


        public decimal Main_Longitude { get; set; }


        public int Distance { get; set; }


        public string FromDateTime { get; set; }

        public string ToDateTime { get; set; }

        public string ParkingClass { get; set; }

        public string OrderBy { get; set; }

        public bool Popularparking { get; set; }
        
        public ParkingAreaViewModel()
        {

        }


    }

    public class ParkingAreaResultViewModel
    {

        public string Parking_id { get; set; }

        public string parking_address { get; set; }

        public string street { get; set; }

        public string city { get; set; }
        public string state { get; set; }
        public string lattitude { get; set; }
        public string longitude { get; set; }
        public string GeoLoc { get; set; }
        public string DateTimeTo { get; set; }
        public string DateTimeFrom { get; set; }
        public string No_Of_Space_Avaiable { get; set; }
        public string Detail_ID { get; set; }
        public int BasicCharge { get; set; }
        public string ParkingClass { get; set; }



    }
}

TestDev/TrueWheels.Web/Controllers/ParkingAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrueWheels.Web.Models;
using TrueWheels.BEL;
using TrueWheels.DAL;
//using TrueWheels.DEL;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Configuration;
using System.Reflection;

namespace TrueWheels.Web.Controllers
{
    public class ParkingAreaController : Controller
    {
        //
        // GET: /ParkingArea/
        
        public ActionResult Index(ParkingAreaViewModel vm)
        {
            ParkingAreaViewModel parkingViewMoel = TempData["ParkingAreaViewModel"] as ParkingAreaViewModel;
            List<AvailableParkingAreaResult> availableParkingList = new List<AvailableParkingAreaResult>();
            ParkingAreaBEL parking = new ParkingAreaBEL();
            parking.Distance = vm.Distance;
            parking.FromDateTime = vm.FromDateTime;
            parking.Main_Latitude = vm.Main_Latitude;
            parking.Main_Longitude = vm.Main_Longitude;
            parking.ParkingClass = vm.ParkingClass;
            parking.ToDateTime = vm.ToDateTime;
            parking.OrderBy = vm.OrderBy;
            parking.PopularParking = vm.Popularparking;
            
            ParkingAreaDAL parkingDal = new ParkingAreaDAL();
            availableParkingList = parkingDal.GetAvailableParking(parking);
            JavaScriptSerializer js = new JavaScriptSerializer();
            var str = js.Serialize(availableParkingList);
            ViewBag.availableParkingList = str;
            if (availableParkingList.Count > 0)
            {
                ViewBag.Lat = availableParkingList[0].lattitude;
                ViewBag.Lng = availableParkingList[0].longitude;
            }
            return View(availableParkingList);
        }

        public ActionResult LocateParkingArea() 
        {
            try
            {
                if (Session["userDetail"] != null)
                {
                    List<UserRating> locateParkingViewModel = new List<UserRating>();
                    UserRating userRating = new UserRating();
                    ParkingAreaDAL parkingDal = new ParkingAreaDAL();
                    locateParkingViewModel = parkingDal.GetParkingRating(Request["parkId"].ToString());

                    return View(locateParkingViewModel.OrderByDescending(x => x.Id));
                    //return View();
                }
                else
                {
                    if (Request["address"] != null)
                        TempData["RequestedUrl"] = "ParkingArea/LocateParkingArea/?lat=" + Request["lat"].ToString() + "&long=" + Request["long"].ToString() + "&address=" + Request["address"].ToString() + "&parkId=" + Request["parkId"].ToString();
                    else
                        TempData["RequestedUrl"] = "ParkingArea/LocateParkingArea/?lat=" + Request["lat"].ToString() + "&long=" + Request["long"].ToString();
                    return RedirectToAction("Login", "TrueWheelsUser");

                }
            }
            catch (Exception ex)
            {
                ExceptionLogging.SendExcepToDB(ex, MethodBase.GetCurrentMethod().Name, this.GetType().Name);
            }
            return RedirectToAction("Login", "TrueWheelsUser");
        }

        [HttpPost]
        public ActionResult AvailableParkingList(string para, string viewModel)
        {
            List<AvailableParkingAreaResult> entity = JsonConvert.DeserializeObject<List<AvailableParkingAreaResult>>(viewModel);
            var result = new List<AvailableParkingAreaResult>();
            if (para == "Distance")
                result = entity.OrderBy(x => x.Distance).ToList();
            else if (para == "Rating")
                result = entity.OrderBy(x => x.Rating).ToList();
            else
                result = entity.OrderBy(x => x.BasicCharge).ToList();
            return PartialView("AvailableParking", result);
        }

        public JsonResult GetParkingdetail(string park_Id)
        {
            ParkingAreaDAL parkingDal = new ParkingAreaDAL();
            var getParkingDetails = parkingDal.GetParkingDetails(park_Id);
            return Json(getParkingDetails, JsonRequestBehavior.AllowGet);
        }

        public void Rating(string para)
        {
            UserRating objUserRating = new UserRating();
            ParkingAreaDAL parkingAreaDAL = new ParkingAreaDAL();
            if (!string.IsNullOrWhiteSpace(para))
            {
                string userId = (((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString();
                string parkingId = HttpUtility.ParseQueryString(Request.UrlReferrer.Query)["parkId"].ToString();

                var response = parkingAreaDAL.InserUpdateUserRating(parkingId, para,userId);


            }
 
        }

        public JsonResult SaveUserComments(UserRating userRating)
        {
           
            UserRating objUserRating = new UserRating();
            objUserRating.success = "false";
            ParkingAreaDAL parkingAreaDAL= new ParkingAreaDAL();
            if (!string.IsNullOrWhiteSpace(userRating.UserComments))
            {
                string userId = (((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString();
               string parkingId = HttpUtility.ParseQueryString(Request.UrlReferrer.Query)["parkId"].ToString();

               objUserRating = parkingAreaDAL.InserUpdateUserComments(userRating.UserComments, userId, parkingId);
               return Json(objUserRating.success, JsonRequestBehavior.AllowGet);
            }
            return Json(objUserRating.success, JsonRequestBehavior.AllowGet);
           
            //return Json("ReviewAndComment",JsonRequestBehavior.AllowGet);
        }

	}
}

TestDev/TrueWheels.Web/Views/ParkingArea/AvailableParking.cshtml
@model List<TrueWheels.BEL.AvailableParkingAreaResult>
@Scripts.Render("~/bundles/Commonjs")
@*<script src="~/Content/js/vendor/jquery-1.10.2.min.js"></script>*@
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
    #markers_info .marker {
        height: 40px;
        cursor: pointer;
        padding-left:40px;
        padding-right:20px;
    }


    .labels {
        color: white;
        background-color: red;
        font-family: "Lucida Grande", "Arial", sans-serif;
        font-size: 10px;
        text-align: center;
        width: 30px;
        white-space: nowrap;
    }
</style>
<script type="text/javascript">
    //$.fn.stars = function () {
    //    return $(this).each(function () {
    //        // Get the value
    //        var val = parseFloat($(this).html());
    //        // Make sure that the value is in 0 - 5 range, multiply to get width
    //        var size = Math.max(0, (Math.min(5, val))) * 16;
    //        // Create stars holder
    //        var $span = $('<span />').width(size);
    //        // Replace the numerical value with stars
    //        $(this).html($span);
    //    });
    //}
    //$(function () {
    //    $('span.stars').stars();
    //});
</script>

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/css/star-rating.min.css" rel="stylesheet" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/Content/js/star-rating.min.js"></script>
<div class="dropdown">
    <button class="btn-blue3 dropdown-toggle" type="button" data-toggle="dropdown">
        Sort By
        <span class="caret"></span>
    </button>
    <ul id="SortOrder" class="dropdown-menu">
        <li><a href="#" onclick="load('Distance')">Distance</a></li>
        <li><a href="#" onclick="load('Basic Charge')">Basic Charge</a></li>
        <li><a href="#" onclick="load('Rating')">Rating</a></li>
    </ul>
</div>
    <div class="col-lg-3" style="overflow:scroll ;height:200vh; padding-left:0px !important; padding-right:0px !important">
        

        <div class="list-group  " id="markers_info">
            @{
                var i = 1;
                foreach (var item in Model)
                {
                    
                    <div style="padding-left:20px;">
                       
                            <span class="badge">@i</span>
                        <a href="#" class="list-group-item marker" style="height:auto; color:#000" onclick='showMap(@item.lattitude,@item.longitude,"@item.parking_address",@item.Parking_id)'>
                            <span class="badge1" style="float:right !important; font-weight:bold;color:#06653A">@item.BasicCharge</span>

                            <span>@item.parking_address</span>
                            <br />
                            <span>@item.BasicCharge</span>
                            @*<div class="c-srp-listing__rating">
                <span>
                    <span class="stars1 rating-meter">
                        <span class="stars_empty"></span>
                        <span class="stars_full" style="width: 94.4%" title=""></span>
                    </span>
                    (1948)
                </span>
            </div>*@
                        </a>
                        <div class="row">
                            <div class="col-lg-12">
                                <input id="input-21a+@item.Parking_id" value="@item.Rating" type="number" class="rating"  min=0 max=5 step=1 data-size="s" readonly="readonly">
                            </div>
                        </div>  
                                <span>@item.Distance</span>
                                @*@item.parking_address<br />*@
                                @*@item.BasicCharge<br />*@
                                @*@item.Rating<br />
                                @item.Distance<br />*@
                                @*<span class="stars">@item.Rating</span>*@
                            
                      
                    </div>

                    i = i + 1;

                }
            }
        </div>
    </div>

@*<script type="text/javascript">
    $(document).ready(function () {

        $('input[id^="input-21a"]').on('rating.change', function (event, value, caption) {
            var parkingId = event.currentTarget.id.split('+')[1]
            debugger;
            $.ajax({
                url: '@Url.Action("Rating", "ParkingArea")',
                dataType: 'html',
                data: { 'para': value, 'parkingId': parkingId },
                type: 'POST',
                success: function (result) {
                    //$('#idAvailableParking').html(result);
                },
                error: function (xhr) {
                    alert(xhr.statusText);
                }
            });

        });
    });

</script>*@



TestDev/TrueWheels.Web/Views/ParkingArea/_ListParking.cshtml
@model IEnumerable<TrueWheels.BEL.AvailableParkingAreaResult>
<html>
<head>
    <title>Index</title>
     <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js"></script>
        <script src="@Url.Content("~/Content/Jquery/tablesorter/themes/blue/style.css")" type="text/javascript"></script>
        <script src="@Url.Content("~/Content/Jquery/tablesorter/jquery.tablesorter.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Content/Jquery/tablesorter/addons/pager/jquery.tablesorter.pager.js")" type="text/javascript"></script>
        <script type="text/javascript">
        $(function () {
            $("table.tablesorter").tablesorter({ widthFixed: true, sortList: [[0, 0]] })
            .tablesorterPager({ container: $("#pager"), size: $(".pagesize option:selected").val() });

        });

        </script>

   
</head>
<body>
    <table id="myTable" class="tablesorter">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Parking_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.parking_address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.state)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lattitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.longitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GeoLoc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTimeFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.No_Of_Space_Avaiable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Detail_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BasicCharge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParkingClass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Distance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Facilities)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpaceType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ErrorMessage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Success)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Parking_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.parking_address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.street)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.state)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lattitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.longitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GeoLoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTimeTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTimeFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.No_Of_Space_Avaiable)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Detail_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasicCharge)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParkingClass)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Distance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Facilities)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpaceType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PropertyType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ErrorMessage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Success)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }

    </table>
</body>
</html>